name: Docker CI

on:
  push: # This will be changed to pull-request once you do the docker setup for repo.
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build Monitor Service
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/cvi-monitor:latest services/monitor
